### PR TITLE
Tentative fixes for issues #62, #63, #64, #65, #66, #68, and #69

### PR DESCRIPTION
**Pull request by rvo-cs**
My take on the above mentioned issues.

(Including cases 1 and 2, as far as #66 is concerned.)

### CODE REVIEW

**Comment by rvo-cs** [comment]
> All checks have passed

Says the Build.

I'm glad for it, but... is it me, or the log looks just like the `main` branch was checked out, rather than a test branch for the PR?
```
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
/usr/bin/git log -1 --format='%H'
'ccfc5a45a25e6c64f888e5381bfc308d30660cf6'
```

**Comment by PhilippSalvisberg** [comment]
Thank you for the pull request, but I'd like to handle the issues case by case.

**Comment by rvo-cs** [comment]
Well...

Issue #66 Case 2 is a technicality, done in [2c12642](https://github.com/PhilippSalvisberg/plscope-utils/pull/70/commits/2c12642222f7f828236c5b44c8d627252e116bc6)

Solving issue #66 Case 1 is done in [fed237f](https://github.com/PhilippSalvisberg/plscope-utils/pull/70/commits/fed237f59789ae19b6eed50e807fd1389a461922).

Issues #62, #63, #64, and #65 are, in fact, linked: if you fix #62 properly, you'll also close the other 3.
That's what is done in [6f9fa47](https://github.com/PhilippSalvisberg/plscope-utils/pull/70/commits/6f9fa47ed16ae08b01568bdd7e2cee30a9a4b472).

It makes sense to implement these fixes in that order because the affected files are mostly always the same (`plscope_tab_usage.sql`, `plscope_col_usage.sql`, `plscope-utils-viewers.sql`, `plscope-utils-reports.sql`), and issue #66 is simple enough, so it's a good starting point.

Issue #69 is separate, and done last in [ca9c30c](https://github.com/PhilippSalvisberg/plscope-utils/pull/70/commits/ca9c30cc4e697630e42cc280dae4baada6981d5b).

I'm not saying that all this should be merged _at once_.

But I insist that these 4 commits each address a distinct issue, or (on the contrary) a set of closely-related issues that it would not make much sense to consider separately.

**Comment by PhilippSalvisberg** [comment]
Thanks. However, I will handle the issues separately. For me it's simply too difficult to review these things in one go. No need for you to submit additional PRs for these issues.

**Pull request closed without merging**
